apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qualys-ca.fullname" . }}-config
  labels:
    {{- include "qualys-ca.labels" . | nindent 4 }}
data:
  QUALYS_SERVER_URI: {{ .Values.config.serverUri | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
